services:
  - type: web
    name: backend-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    plan: free
    branch: main
    rootDir: backend

staticSites:
  - name: react-vite-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    branch: main
    rootDir: .
    envVars:
      - key: VITE_API_URL
        value: https://backend-service.onrender.com
